platform :ios, '8.0'
target 'QuPassenger' do
pod 'AFNetworking','~>3.1.0'
pod 'MJExtension','~>3.0.13'
pod 'IQKeyboardManager','~>4.0.13'
pod 'Masonry','~>1.0.2'
pod 'MJRefresh','~>3.1.12'
pod 'MBProgressHUD','~>1.0.0'
pod 'SDWebImage','~>4.0.0'
pod 'WZLBadge'
pod 'SAMKeychain'
pod 'SVProgressHUD'
pod 'JPush'
pod 'FMDB'
pod 'MJNIndexView'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'UMengAnalytics-NO-IDFA'
# 主模块(必须)
pod 'ShareSDK3'
pod 'MOBFoundation'
# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
pod 'ShareSDK3/ShareSDKUI'
# 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
# 扩展模块（在调用可以弹出我们UI分享方法的时候是必需的）
pod 'ShareSDK3/ShareSDKExtension'
end
