platform :ios, '8.0'
target 'QuPassenger' do
pod 'AFNetworking','~>3.1.0'
pod 'MJExtension','~>3.0.13'
pod 'IQKeyboardManager','~>4.0.8'
pod 'Masonry','~>1.0.2'
pod 'MJRefresh','~>3.1.12'
pod 'MBProgressHUD','~>1.0.0'
pod 'SDWebImage','~>4.0.0'
pod 'DZNEmptyDataSet', '~> 1.8.1'
end
